POST {{hostname}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  createComplaint(input: {first_name: "Mubarek", gender: "male",  last_name: "Mohamed", rating: 6, complaintable: {
    connect: 1,
    type: "office"
  }, complaint_description: "'complaint_description' doesn't have a default value (SQL: insert into `complaints` (`first_name`, `last_name`, `rating`, `complaintable_id`, `complaintable_type`, ",
  	complaint_type: "complaint", 
  defined_complaint_id: null}) {
    id
    title
    description
  }  
}
